# Generated by Django 3.2.7 on 2021-09-18 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0002_auto_20210915_2213'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'ordering': ['first_name'], 'verbose_name': 'Author', 'verbose_name_plural': 'Authors'},
        ),
    ]
